import {
  ChevronLeft,
  ChevronRight,
  Check,
  ChevronDown,
  Contact,
  Copy,
  Database,
  Download,
  FileText,
  History,
  LayoutDashboard,
  ListFilter,
  LogIn,
  Pencil,
  Plus,
  RefreshCw,
  Send,
  SendHorizontal,
  Settings,
  ShieldCheck,
  Trash2,
  Upload,
  UserMinus,
  UserPlus,
  UsersRound,
  X,
  createIcons,
} from 'lucide';

const APP_ICONS = {
  ChevronLeft,
  ChevronRight,
  Check,
  ChevronDown,
  Contact,
  Copy,
  Database,
  Download,
  FileText,
  History,
  LayoutDashboard,
  ListFilter,
  LogIn,
  Pencil,
  Plus,
  RefreshCw,
  Send,
  SendHorizontal,
  Settings,
  ShieldCheck,
  Trash2,
  Upload,
  UserMinus,
  UserPlus,
  UsersRound,
  X,
};

/** Render icons from the explicit app registry to keep the bundled icon set intentional. */
export function renderIcons(root: Element): void {
  createIcons({
    icons: APP_ICONS,
    attrs: { class: 'ui-icon', width: 18, height: 18, 'stroke-width': 2, 'aria-hidden': 'true' },
    root,
  });
}
