/** Whitelist of IPC channels exposed to the renderer. */
export const CHANNELS = [
  'setup:status',
  'setup:test-db',
  'setup:save-db',
  'setup:init-db',
  'setup:bootstrap',
  'settings:get-sms-provider',
  'settings:save-sms-provider',
  'auth:login',
  'contacts:list',
  'contacts:create',
  'contacts:update',
  'contacts:delete',
  'contacts:bulk-delete',
  'contacts:import',
  'groups:list',
  'groups:create',
  'groups:update',
  'groups:delete',
  'users:list',
  'users:create',
  'users:update',
  'users:delete',
  'sms:list',
  'sms:queue',
  'sms:send',
  'sms:test-connection'
] as const;
export type Channel = (typeof CHANNELS)[number];
